---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-docker
  name: spring-docker
  namespace: easypay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-docker
      role: frontend
  template:
    metadata:
      labels:
        app: spring-docker
        role: frontend
    spec:
      containers:
      - image: profed11/spring-boot-docker:latest
        name: springboot
        ports:
        - containerPort: 8080
          name: springboot
        resources:
           limits:
             cpu: 200m  ## 20% of the 1 core cpu = 1000 milli cpu on the vm

