---
- hosts: localhost
  remote_user: root
  tasks:
  - name: Create security group
    ec2_group:
        name: ec2-easypay
        description: ec2-easypay security group
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: "{{ region }}"
        rules:
          - proto: tcp  # ssh
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # http
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # https
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    register: firewall_sg

  - name: Create a new EC2 key
    ec2_key:
      name: ec2-easypay-key
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "{{ region }}"
      key_material: "{{ lookup('file', '/Users/edwardhanks/.ssh/id_rsa.pub') }}"

  - name: Create an EC2 instance
    ec2:
      key_name: ec2-easypay-key
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "{{ region }}"
      group_id: sg-0b143620be13fb012
      instance_type: t2.micro
      image: ami-0149b2da6ceec4bb0
      wait: yes
      instance_tags:
        Name: ec2_easypay-key
      count_tag: Name        
      exact_count: 1
      vpc_subnet_id: subnet-02eba492cde6d5305
      assign_public_ip: yes
    register: ec2

